/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#636565',
        'surface': '#121414',
        'secondary': '#e9c176',
        'surface-variant': '#343535',
        'on-error': '#690005',
        'tertiary-container': '#e2e2e2',
        'primary-container': '#e2e2e2',
        'on-primary': '#2f3131',
        'surface-container': '#1f2020',
        'surface-container-low': '#1b1c1c',
        'on-surface-variant': '#c4c7c8',
        'primary-fixed-dim': '#c6c6c7',
        'inverse-on-surface': '#2f3031',
        'background': '#121414',
        'outline-variant': '#444748',
        'tertiary': '#ffffff',
        'on-background': '#e3e2e2',
        'surface-dim': '#121414',
        'surface-tint': '#c6c6c7',
        'on-secondary': '#412d00',
        'inverse-primary': '#5d5f5f',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary': '#2f3131',
        'surface-container-high': '#292a2a',
        'surface-container-highest': '#343535',
        'surface-bright': '#383939',
        'secondary-fixed': '#ffdea5',
        'secondary-fixed-dim': '#e9c176',
        'secondary-container': '#604403',
        'outline': '#8e9192',
        'on-primary-container': '#636565',
        'primary-fixed': '#e2e2e2',
        'on-error-container': '#ffdad6',
        'on-surface': '#e3e2e2',
        'error-container': '#93000a',
        'on-secondary-container': '#dab36a',
        'surface-container-lowest': '#0d0e0f',
        'error': '#ffb4ab',
        'on-secondary-fixed': '#261900',
        'primary': '#ffffff',
        'inverse-surface': '#e3e2e2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-x': '64px',
        'section-gap': '160px',
        unit: '8px',
        gutter: '32px',
        'container-max': '1440px',
      },
      fontFamily: {
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'display-xl': ['Syne', 'sans-serif'],
        'headline-md': ['Syne', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Syne', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['20px', { lineHeight: '32px', letterSpacing: '0em', fontWeight: '400' }],
        'display-xl': ['120px', { lineHeight: '110px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-md': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.2em', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'marquee': {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        }
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.8s ease forwards',
        'fade-in': 'fade-in 1s ease forwards',
        'marquee': 'marquee 20s linear infinite',
      }
    },
  },
  plugins: [],
};
